// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/charitan-go/project-server/ent/project"
	"github.com/charitan-go/project-server/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescReadableID is the schema descriptor for readable_id field.
	projectDescReadableID := projectFields[1].Descriptor()
	// project.DefaultReadableID holds the default value on creation for the readable_id field.
	project.DefaultReadableID = projectDescReadableID.Default.(func() uuid.UUID)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[2].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[3].Descriptor()
	// project.DefaultDescription holds the default value on creation for the description field.
	project.DefaultDescription = projectDescDescription.Default.(string)
	// projectDescGoal is the schema descriptor for goal field.
	projectDescGoal := projectFields[4].Descriptor()
	// project.GoalValidator is a validator for the "goal" field. It is called by the builders before save.
	project.GoalValidator = projectDescGoal.Validators[0].(func(float64) error)
	// projectDescCountryCode is the schema descriptor for countryCode field.
	projectDescCountryCode := projectFields[8].Descriptor()
	// project.CountryCodeValidator is a validator for the "countryCode" field. It is called by the builders before save.
	project.CountryCodeValidator = projectDescCountryCode.Validators[0].(func(string) error)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
}
